/* Copyright Statement:
 *
 * This software/firmware and related documentation ("AutoChips Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to AutoChips Inc. and/or its licensors. Without
 * the prior written permission of AutoChips inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of AutoChips Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 *
 * AutoChips Inc. (C) 2023. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AUTOCHIPS SOFTWARE")
 * RECEIVED FROM AUTOCHIPS AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. AUTOCHIPS EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES AUTOCHIPS PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE AUTOCHIPS SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN AUTOCHIPS
 * SOFTWARE. AUTOCHIPS SHALL ALSO NOT BE RESPONSIBLE FOR ANY AUTOCHIPS SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AUTOCHIPS'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE AUTOCHIPS SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT AUTOCHIPS'S OPTION, TO REVISE OR REPLACE THE
 * AUTOCHIPS SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO AUTOCHIPS FOR SUCH AUTOCHIPS SOFTWARE AT ISSUE.
 */

// Amount of memory (in bytes) allocated for Stack
// Tailor this value to your application needs
// <h> Stack Configuration
//   <o> Stack Size (in Bytes) <0x0-0xFFFFFFFF:8>
// </h>

    .file "startup_ac7843x.s"
    .arch armv7e-m
    .text

    .thumb

    .section .isr_vector
    .align 2
    .globl __Vectors
__Vectors:
    .long   __StackTop                                      // Top of Stack
    .long   Reset_Handler                                   // Reset Handler
    .long   NMI_Handler                                     // NMI Handler
    .long   HardFault_Handler                               // Hard Fault Handler
    .long   MemManage_Handler                               // MPU Fault Handler
    .long   BusFault_Handler                                // Bus Fault Handler
    .long   UsageFault_Handler                              // Usage Fault Handler
    .long   0                                               // Reserved
    .long   0                                               // Reserved
    .long   0                                               // Reserved
    .long   0                                               // Reserved
    .long   SVC_Handler                                     // SVCall Handler
    .long   DebugMon_Handler                                // Debug Monitor Handler
    .long   0                                               // Reserved
    .long   PendSV_Handler                                  // PendSV Handler
    .long   SysTick_Handler                                 // SysTick Handler

// External interrupts
    .long     DMA0_Channel0_IRQHandler            //DMA channel 0 Interrupt
    .long     DMA0_Channel1_IRQHandler            //DMA channel 1 Interrupt
    .long     DMA0_Channel2_IRQHandler            //DMA channel 2 Interrupt
    .long     DMA0_Channel3_IRQHandler            //DMA channel 3 Interrupt
    .long     DMA0_Channel4_IRQHandler            //DMA channel 4 Interrupt
    .long     DMA0_Channel5_IRQHandler            //DMA channel 5 Interrupt
    .long     DMA0_Channel6_IRQHandler            //DMA channel 6 Interrupt
    .long     DMA0_Channel7_IRQHandler            //DMA channel 7 Interrupt
    .long     DMA0_Channel8_IRQHandler            //DMA channel 8 Interrupt
    .long     DMA0_Channel9_IRQHandler            //DMA channel 9 Interrupt
    .long     DMA0_Channel10_IRQHandler           //DMA channel 10 Interrupt
    .long     DMA0_Channel11_IRQHandler           //DMA channel 11 Interrupt
    .long     DMA0_Channel12_IRQHandler           //DMA channel 12 Interrupt
    .long     DMA0_Channel13_IRQHandler           //DMA channel 13 Interrupt
    .long     DMA0_Channel14_IRQHandler           //DMA channel 14 Interrupt
    .long     DMA0_Channel15_IRQHandler           //DMA channel 15 Interrupt
    .long     0                                   //Reserved
    .long     0                                   //Reserved
    .long     0                                   //Reserved
    .long     0                                   //Reserved
    .long     0                                   //Reserved
    .long     0                                   //Reserved
    .long     0                                   //Reserved
    .long     0                                   //Reserved
    .long     PORTA_IRQHandler                    //Port A pin detect interruptInterrupt
    .long     PORTB_IRQHandler                    //Port B pin detect interrupt
    .long     PORTC_IRQHandler                    //Port C pin detect interrupt
    .long     PORTD_IRQHandler                    //Port D pin detect interrupt
    .long     PORTE_IRQHandler                    //Port E pin detect interrupt
    .long     UART0_IRQHandler                    //UART0 Transmit / Receive Interrupt
    .long     UART1_IRQHandler                    //UART1 Transmit / Receive Interrupt
    .long     UART2_IRQHandler                    //UART2 Transmit / Receive Interrupt
    .long     UART3_IRQHandler                    //UART3 Transmit / Receive Interrupt
    .long     UART4_IRQHandler                    //UART4 Interrupt
    .long     UART5_IRQHandler                    //UART5 Interrupt
    .long     UART6_IRQHandler                    //UART6 Interrupt
    .long     UART7_IRQHandler                    //UART7 Interrupt
    .long     SPI0_IRQHandler                     //SPI0 Interrupt
    .long     SPI1_IRQHandler                     //SPI1 Interrupt
    .long     SPI2_IRQHandler                     //SPI2 Interrupt
    .long     SPI3_IRQHandler                     //SPI3 Interrupt
    .long     SPI4_IRQHandler                     //SPI4 Interrupt
    .long     I2C0_IRQHandler                     //I2C0 Interrupt
    .long     I2C1_IRQHandler                     //I2C1 Interrupt
    .long     I2C2_IRQHandler                     //I2C2 Interrupt
    .long     EIO_IRQHandler                      //EIO Interrupt
    .long     CAN0_IRQHandler                     //CAN0 Interrupt
    .long     CAN0_Wakeup_IRQHandler              //CAN0 Wakeup Interrupt
    .long     CAN0_DMU_IRQHandler                 //CAN0 DMU Interrupt
    .long     CAN1_IRQHandler                     //CAN1 Interrupt
    .long     CAN1_Wakeup_IRQHandler              //CAN1 Wakeup Interrupt
    .long     CAN1_DMU_IRQHandler                 //CAN1 DMU Interrupt
    .long     CAN2_IRQHandler                     //CAN2 Interrupt
    .long     CAN2_Wakeup_IRQHandler              //CAN2 Wakeup Interrupt
    .long     CAN2_DMU_IRQHandler                 //CAN2 DMU Interrupt
    .long     CAN3_IRQHandler                     //CAN3 Interrupt
    .long     CAN3_Wakeup_IRQHandler              //CAN3 Wakeup Interrupt
    .long     CAN3_DMU_IRQHandler                 //CAN3 DMU Interrupt
    .long     CAN4_IRQHandler                     //CAN4 Interrupt
    .long     CAN4_Wakeup_IRQHandler              //CAN4 Wakeup Interrupt
    .long     CAN4_DMU_IRQHandler                 //CAN4 DMU Interrupt
    .long     CAN5_IRQHandler                     //CAN5 Interrupt
    .long     CAN5_Wakeup_IRQHandler              //CAN5 Wakeup Interrupt
    .long     CAN5_DMU_IRQHandler                 //CAN5 DMU Interrupt
    .long     PDT0_IRQHandler                     //PDT0 Interrupt
    .long     PDT1_IRQHandler                     //PDT1 Interrupt
    .long     ADC0_IRQHandler                     //ADC0 Interrupt
    .long     ADC1_IRQHandler                     //ADC1 Interrupt
    .long     ACMP0_IRQHandler                    //ACMP0 Interrupt
    .long     ACMP1_IRQHandler                    //ACMP1 Interrupt
    .long     WDG_IRQHandler                      //WDG Interrupt
    .long     EWDG_IRQHandler                     //EWDG Interrupt
    .long     MCM_IRQHandler                      //MCM Interrupt
    .long     LVD_IRQHandler                      //LVD Interrupt
    .long     SPM_IRQHandler                      //SPM Interrupt
    .long     RCM_IRQHandler                      //RCM Interrupt
    .long     PWM0_Overflow_IRQHandler            //PWM0 Overflow Interrupt
    .long     PWM0_Channel_IRQHandler             //PWM0 Channel Interrupt
    .long     PWM0_Fault_IRQHandler               //PWM0 Fault Interrupt
    .long     PWM0_Detect_IRQHandler              //PWM0 Detect Interrupt
    .long     PWM1_Overflow_IRQHandler            //PWM1 Overflow Interrupt
    .long     PWM1_Channel_IRQHandler             //PWM1 Channel Interrupt
    .long     PWM1_Fault_IRQHandler               //PWM1 Fault Interrupt
    .long     PWM1_Detect_IRQHandler              //PWM1 Detect Interrupt
    .long     PWM2_Overflow_IRQHandler            //PWM2 Overflow Interrupt
    .long     PWM2_Channel_IRQHandler             //PWM2 Channel Interrupt
    .long     PWM2_Fault_IRQHandler               //PWM2 Fault Interrupt
    .long     PWM2_Detect_IRQHandler              //PWM2 Detect Interrupt
    .long     PWM3_Overflow_IRQHandler            //PWM3 Overflow Interrupt
    .long     PWM3_Channel_IRQHandler             //PWM3 Channel Interrupt
    .long     PWM3_Fault_IRQHandler               //PWM3 Fault Interrupt
    .long     PWM3_Detect_IRQHandler              //PWM3 Detect Interrupt
    .long     PWM4_Overflow_IRQHandler            //PWM4 Overflow Interrupt
    .long     PWM4_Channel_IRQHandler             //PWM4 Channel Interrupt
    .long     PWM4_Fault_IRQHandler               //PWM4 Fault Interrupt
    .long     PWM4_Detect_IRQHandler              //PWM4 Detect Interrupt
    .long     PWM5_Overflow_IRQHandler            //PWM5 Overflow Interrupt
    .long     PWM5_Channel_IRQHandler             //PWM5 Channel Interrupt
    .long     PWM5_Fault_IRQHandler               //PWM5 Fault Interrupt
    .long     PWM5_Detect_IRQHandler              //PWM5 Detect Interrupt
    .long     PWM6_Overflow_IRQHandler            //PWM6 Overflow Interrupt
    .long     PWM6_Channel_IRQHandler             //PWM6 Channel Interrupt
    .long     PWM6_Fault_IRQHandler               //PWM6 Fault Interrupt
    .long     PWM6_Detect_IRQHandler              //PWM6 Detect Interrupt
    .long     PWM7_Overflow_IRQHandler            //PWM7 Overflow Interrupt
    .long     PWM7_Channel_IRQHandler             //PWM7 Channel Interrupt
    .long     PWM7_Fault_IRQHandler               //PWM7 Fault Interrupt
    .long     PWM7_Detect_IRQHandler              //PWM7 Detect Interrupt
    .long     RTC_IRQHandler                      //RTC Interrupt
    .long     PCT_IRQHandler                      //PCT Interrupt
    .long     TIMER_Channel0_IRQHandler           //TIMER Channel0 Interrupt
    .long     TIMER_Channel1_IRQHandler           //TIMER Channel1 Interrupt
    .long     TIMER_Channel2_IRQHandler           //TIMER Channel2 Interrupt
    .long     TIMER_Channel3_IRQHandler           //TIMER Channel3 Interrupt
    .long     HSM_IRQHandler                      //HSM Interrupt
    .long     FLASH_ECC_IRQHandler                //Flash ECC Interrupt
    .long     FLASH_IRQHandler                    //Flash Interrupt
    .long     FLASH_Collision_IRQHandler          //Flash Collision Interrupt
    .long     ECC_1BIT_IRQHandler                 //ECC 1BIT Interrupt
    .long     ECC_2BIT_IRQHandler                 //ECC 2BIT Interrupt
    .long     SENT_Channel0_IRQHandler            //SENT Channel 0 Interrupt
    .long     SENT_Channel1_IRQHandler            //SENT Channel 1 Interrupt
    .long     SENT_Channel2_IRQHandler            //SENT Channel 2 Interrupt
    .long     SENT_Channel3_IRQHandler            //SENT Channel 3 Interrupt
    .long     SMU_IRQHandler                      //SMU Interrupt
    .long     STB_WU_IRQHandler                   //Standby Wakeup Interrupt

    .long     DefaultISR
    .size    __Vectors, . - __Vectors

    .text
    .thumb

// Reset Handler
    .thumb_func
    .align 2
    .globl   Reset_Handler
    .weak    Reset_Handler
    .type    Reset_Handler, %function
Reset_Handler:
    mrs     r10,primask     // Save PRIMASK
    cpsid   i               // Mask interrupts

    // Initialize the stack pointer
    ldr     r1,=__StackTop
    mov     r13,r1

    // Init ECC SRAM
    ldr     r0,=STACK_SIZE
    sub     r0, r1, r0
    ldr     r3,=SystemInitRam
    blx     r3

    // Call the CMSIS system init routine
    ldr     r0,=SystemInit
    blx     r0

    msr     primask,r10     // Restore PRIMASK
    bl      main

    .pool
    .size Reset_Handler, . - Reset_Handler

    .align  1
    .thumb
    .thumb_func
    .weak DefaultISR
    .type DefaultISR, %function
DefaultISR:
    b       .
    .size DefaultISR, . - DefaultISR

/*    Macro to define default handlers. Default handler
 *    will be weak symbol and just dead loops. They can be
 *    overwritten by other handlers */
    .macro def_irq_handler    handler_name
    .weak \handler_name
    .set  \handler_name, DefaultISR
    .endm

// Exception Handlers
    def_irq_handler    NMI_Handler                         //NMI Handler
    def_irq_handler    HardFault_Handler                   //Hard Fault Handler
    def_irq_handler    MemManage_Handler                   //MPU Fault Handler
    def_irq_handler    BusFault_Handler                    //Bus Fault Handler
    def_irq_handler    UsageFault_Handler                  //Usage Fault Handler
    def_irq_handler    SVC_Handler                         //SVCall Handler
    def_irq_handler    DebugMon_Handler                    //Debug Monitor Handle
    def_irq_handler    PendSV_Handler                      //PendSV Handler
    def_irq_handler    SysTick_Handler                     //SysTick Handler
    def_irq_handler    DMA0_Channel0_IRQHandler            //DMA channel 0 Interrupt
    def_irq_handler    DMA0_Channel1_IRQHandler            //DMA channel 1 Interrupt
    def_irq_handler    DMA0_Channel2_IRQHandler            //DMA channel 2 Interrupt
    def_irq_handler    DMA0_Channel3_IRQHandler            //DMA channel 3 Interrupt
    def_irq_handler    DMA0_Channel4_IRQHandler            //DMA channel 4 Interrupt
    def_irq_handler    DMA0_Channel5_IRQHandler            //DMA channel 5 Interrupt
    def_irq_handler    DMA0_Channel6_IRQHandler            //DMA channel 6 Interrupt
    def_irq_handler    DMA0_Channel7_IRQHandler            //DMA channel 7 Interrupt
    def_irq_handler    DMA0_Channel8_IRQHandler            //DMA channel 8 Interrupt
    def_irq_handler    DMA0_Channel9_IRQHandler            //DMA channel 9 Interrupt
    def_irq_handler    DMA0_Channel10_IRQHandler           //DMA channel 10 Interrupt
    def_irq_handler    DMA0_Channel11_IRQHandler           //DMA channel 11 Interrupt
    def_irq_handler    DMA0_Channel12_IRQHandler           //DMA channel 12 Interrupt
    def_irq_handler    DMA0_Channel13_IRQHandler           //DMA channel 13 Interrupt
    def_irq_handler    DMA0_Channel14_IRQHandler           //DMA channel 14 Interrupt
    def_irq_handler    DMA0_Channel15_IRQHandler           //DMA channel 15 Interrupt
    def_irq_handler    PORTA_IRQHandler                    //Port A pin detect interrupt
    def_irq_handler    PORTB_IRQHandler                    //Port B pin detect interrupt
    def_irq_handler    PORTC_IRQHandler                    //Port C pin detect interrupt
    def_irq_handler    PORTD_IRQHandler                    //Port D pin detect interrupt
    def_irq_handler    PORTE_IRQHandler                    //Port E pin detect interrupt
    def_irq_handler    UART0_IRQHandler                    //UART0 Transmit / Receive Interrupt
    def_irq_handler    UART1_IRQHandler                    //UART1 Transmit / Receive Interrupt
    def_irq_handler    UART2_IRQHandler                    //UART2 Transmit / Receive Interrupt
    def_irq_handler    UART3_IRQHandler                    //UART3 Transmit / Receive Interrupt
    def_irq_handler    UART4_IRQHandler                    //UART4 Transmit / Receive Interrupt
    def_irq_handler    UART5_IRQHandler                    //UART5 Transmit / Receive Interrupt
    def_irq_handler    UART6_IRQHandler                    //UART6 Transmit / Receive Interrupt
    def_irq_handler    UART7_IRQHandler                    //UART7 Transmit / Receive Interrupt
    def_irq_handler    SPI0_IRQHandler                     //SPI0 Interrupt
    def_irq_handler    SPI1_IRQHandler                     //SPI1 Interrupt
    def_irq_handler    SPI2_IRQHandler                     //SPI2 Interrupt
    def_irq_handler    SPI3_IRQHandler                     //SPI3 Interrupt
    def_irq_handler    SPI4_IRQHandler                     //SPI4 Interrupt
    def_irq_handler    I2C0_IRQHandler                     //I2C0 Interrupt
    def_irq_handler    I2C1_IRQHandler                     //I2C1 Interrupt
    def_irq_handler    I2C2_IRQHandler                     //I2C2 Interrupt
    def_irq_handler    EIO_IRQHandler                      //EIO Interrupt
    def_irq_handler    CAN0_IRQHandler                     //CAN0 Interrupt
    def_irq_handler    CAN0_Wakeup_IRQHandler              //CAN0 Wakeup Interrupt
    def_irq_handler    CAN0_DMU_IRQHandler                 //CAN0 DMU Interrupt
    def_irq_handler    CAN1_IRQHandler                     //CAN1 Interrupt
    def_irq_handler    CAN1_Wakeup_IRQHandler              //CAN1 Wakeup Interrupt
    def_irq_handler    CAN1_DMU_IRQHandler                 //CAN1 DMU Interrupt
    def_irq_handler    CAN2_IRQHandler                     //CAN2 Interrupt
    def_irq_handler    CAN2_Wakeup_IRQHandler              //CAN2 Wakeup Interrupt
    def_irq_handler    CAN2_DMU_IRQHandler                 //CAN2 DMU Interrupt
    def_irq_handler    CAN3_IRQHandler                     //CAN3 Interrupt
    def_irq_handler    CAN3_Wakeup_IRQHandler              //CAN3 Wakeup Interrupt
    def_irq_handler    CAN3_DMU_IRQHandler                 //CAN3 DMU Interrupt
    def_irq_handler    CAN4_IRQHandler                     //CAN4 Interrupt
    def_irq_handler    CAN4_Wakeup_IRQHandler              //CAN4 Wakeup Interrupt
    def_irq_handler    CAN4_DMU_IRQHandler                 //CAN4 DMU Interrupt
    def_irq_handler    CAN5_IRQHandler                     //CAN5 Interrupt
    def_irq_handler    CAN5_Wakeup_IRQHandler              //CAN5 Wakeup Interrupt
    def_irq_handler    CAN5_DMU_IRQHandler                 //CAN5 DMU Interrupt
    def_irq_handler    PDT0_IRQHandler                     //PDT0 Interrupt
    def_irq_handler    PDT1_IRQHandler                     //PDT1 Interrupt
    def_irq_handler    ADC0_IRQHandler                     //ADC0 Interrupt
    def_irq_handler    ADC1_IRQHandler                     //ADC1 Interrupt
    def_irq_handler    ACMP0_IRQHandler                    //ACMP0 Interrupt
    def_irq_handler    ACMP1_IRQHandler                    //ACMP1 Interrupt
    def_irq_handler    WDG_IRQHandler                      //WDG Interrupt
    def_irq_handler    EWDG_IRQHandler                     //EWDG Interrupt
    def_irq_handler    MCM_IRQHandler                      //MCM Interrupt
    def_irq_handler    LVD_IRQHandler                      //LVD Interrupt
    def_irq_handler    SPM_IRQHandler                      //SPM Interrupt
    def_irq_handler    RCM_IRQHandler                      //RCM Interrupt
    def_irq_handler    PWM0_Overflow_IRQHandler            //PWM0 Overflow Interrupt
    def_irq_handler    PWM0_Channel_IRQHandler             //PWM0 Channel Interrupt
    def_irq_handler    PWM0_Fault_IRQHandler               //PWM0 Fault Interrupt
    def_irq_handler    PWM0_Detect_IRQHandler              //PWM0 Detect Interrupt
    def_irq_handler    PWM1_Overflow_IRQHandler            //PWM1 Overflow Interrupt
    def_irq_handler    PWM1_Channel_IRQHandler             //PWM1 Channel Interrupt
    def_irq_handler    PWM1_Fault_IRQHandler               //PWM1 Fault Interrupt
    def_irq_handler    PWM1_Detect_IRQHandler              //PWM1 Detect Interrupt
    def_irq_handler    PWM2_Overflow_IRQHandler            //PWM2 Overflow Interrupt
    def_irq_handler    PWM2_Channel_IRQHandler             //PWM2 Channel Interrupt
    def_irq_handler    PWM2_Fault_IRQHandler               //PWM2 Fault Interrupt
    def_irq_handler    PWM2_Detect_IRQHandler              //PWM2 Detect Interrupt
    def_irq_handler    PWM3_Overflow_IRQHandler            //PWM3 Overflow Interrupt
    def_irq_handler    PWM3_Channel_IRQHandler             //PWM3 Channel Interrupt
    def_irq_handler    PWM3_Fault_IRQHandler               //PWM3 Fault Interrupt
    def_irq_handler    PWM3_Detect_IRQHandler              //PWM3 Detect Interrupt
    def_irq_handler    PWM4_Overflow_IRQHandler            //PWM4 Overflow Interrupt
    def_irq_handler    PWM4_Channel_IRQHandler             //PWM4 Channel Interrupt
    def_irq_handler    PWM4_Fault_IRQHandler               //PWM4 Fault Interrupt
    def_irq_handler    PWM4_Detect_IRQHandler              //PWM4 Detect Interrupt
    def_irq_handler    PWM5_Overflow_IRQHandler            //PWM5 Overflow Interrupt
    def_irq_handler    PWM5_Channel_IRQHandler             //PWM5 Channel Interrupt
    def_irq_handler    PWM5_Fault_IRQHandler               //PWM5 Fault Interrupt
    def_irq_handler    PWM5_Detect_IRQHandler              //PWM5 Detect Interrupt
    def_irq_handler    PWM6_Overflow_IRQHandler            //PWM6 Overflow Interrupt
    def_irq_handler    PWM6_Channel_IRQHandler             //PWM6 Channel Interrupt
    def_irq_handler    PWM6_Fault_IRQHandler               //PWM6 Fault Interrupt
    def_irq_handler    PWM6_Detect_IRQHandler              //PWM6 Detect Interrupt
    def_irq_handler    PWM7_Overflow_IRQHandler            //PWM7 Overflow Interrupt
    def_irq_handler    PWM7_Channel_IRQHandler             //PWM7 Channel Interrupt
    def_irq_handler    PWM7_Fault_IRQHandler               //PWM7 Fault Interrupt
    def_irq_handler    PWM7_Detect_IRQHandler              //PWM7 Detect Interrupt
    def_irq_handler    RTC_IRQHandler                      //RTC Interrupt
    def_irq_handler    PCT_IRQHandler                      //PCT Interrupt
    def_irq_handler    TIMER_Channel0_IRQHandler           //TIMER Channel0 Interrupt
    def_irq_handler    TIMER_Channel1_IRQHandler           //TIMER Channel1 Interrupt
    def_irq_handler    TIMER_Channel2_IRQHandler           //TIMER Channel2 Interrupt
    def_irq_handler    TIMER_Channel3_IRQHandler           //TIMER Channel3 Interrupt
    def_irq_handler    HSM_IRQHandler                      //HSM Interrupt
    def_irq_handler    FLASH_ECC_IRQHandler                //Flash ECC Interrupt
    def_irq_handler    FLASH_IRQHandler                    //Flash Interrupt
    def_irq_handler    FLASH_Collision_IRQHandler          //Flash Collision Interrupt
    def_irq_handler    ECC_1BIT_IRQHandler                 //ECC 1BIT Interrupt
    def_irq_handler    ECC_2BIT_IRQHandler                 //ECC 2BIT Interrupt
    def_irq_handler    SENT_Channel0_IRQHandler            //SENT CHANNEL 0 Interrupt
    def_irq_handler    SENT_Channel1_IRQHandler            //SENT CHANNEL 1 Interrupt
    def_irq_handler    SENT_Channel2_IRQHandler            //SENT CHANNEL 2 Interrupt
    def_irq_handler    SENT_Channel3_IRQHandler            //SENT CHANNEL 3 Interrupt
    def_irq_handler    SMU_IRQHandler                      //SAFETY MONITOR UNIT Interrupt
    def_irq_handler    STB_WU_IRQHandler                   //Standby Wakeup Interrupt
    .end

