#ifndef __HPM_CONTENT_H__
#define __HPM_CONTENT_H__

#define HPM_APP_CYCLE_INTV (1 * 1000)

#define HPM_SESSION_LOG_MEM_SIZE (256)
#define HPM_SESSION_HTBT_MEM_SIZE (64)
#define HPM_SESSION_COMMON_MEM_SIZE (1024)
#define HPM_SESSION_RECV_MEM_SIZE (512)

#define HPM_PACK_HEAD_MEM_SIZE (64)

#define HPM_OTA_TBOX_INFO_NAME		("HPM_OTA_TBOX_INFO")
#define HPM_OTA_TBOX_MAGIC_NO		(0x11223344)

typedef enum
{
    HPM_CFG_TSP_PARA_MIN = 0x0001,
    HPM_CFG_TSP_PARA_APN = 0x0001,
    HPM_CFG_TSP_PARA_MAIN_IP = 0x0002,
    HPM_CFG_TSP_PARA_MAIN_URL = 0x0003,
    HPM_CFG_TSP_PARA_SLAVER_IP = 0x0004,
    HPM_CFG_TSP_PARA_SLAVER_URL = 0x0005,
    HPM_CFG_TSP_PARA_MAIN_PORT = 0x0006,
    HPM_CFG_TSP_PARA_SLAVER_PORT = 0x0007,
    HPM_CFG_TSP_PARA_HEART_BEAT_INTV = 0x0008,
    HPM_CFG_TSP_PARA_ENTER_SLEEP_TIME = 0x0009,
    HPM_CFG_TSP_PARA_REAL_DATA_INTV = 0x000A,
    HPM_CFG_TSP_PARA_SOFT_VER = 0x0101,
    HPM_CFG_TSP_PARA_HARD_VER = 0x0102,
    HPM_CFG_TSP_PARA_ACC_TOTAL_TIME = 0x0103,
    HPM_CFG_TSP_PARA_ACC_TOTAL_DIS = 0x0104,
    HPM_CFG_TSP_PARA_SLEEP_MODE_ENBLE = 0x0105,
    HPM_CFG_TSP_PARA_TIME_ZONE = 0x0106,
    HPM_CFG_TSP_PARA_VIN = 0x0107,
    HPM_CFG_TSP_PARA_OBD_TYPE = 0x0108,
    HPM_CFG_TSP_PARA_CAN1_BAUD = 0x0109,
    HPM_CFG_TSP_PARA_CAN2_BAUD = 0x010A,
    HPM_CFG_TSP_PARA_CAN3_BAUD = 0x010B,
    HPM_CFG_TSP_PARA_GPS_MODE = 0x010C,
    HPM_CFG_TSP_PARA_MAX = HPM_CFG_TSP_PARA_GPS_MODE,
} HPM_CFG_PARAM_ID;

typedef enum
{
    HPM_CFG_RESP_OK = 0x00,
    HPM_CFG_RESP_NG = 0x01,
} HPM_CFG_RESP_RESULT;

extern SemaphoreHandle_t hpm_mutex;

#define HPM_MUTEX_LOCK() xSemaphoreTake(hpm_mutex, portMAX_DELAY)
#define HPM_MUTEX_UNLOCK() xSemaphoreGive(hpm_mutex)

#endif
