#ifndef TBOX_4G_AT_STARTUP_H
#define TBOX_4G_AT_STARTUP_H

typedef enum
{
    AT_4G_STARTUP_IDLE = 0,
    AT_4G_STARTUP_WAIRFOR_4GMODULE_STARTUP,
    AT_4G_STARTUP_TESTLIVE,
    AT_4G_STARTUP_WAITFOR_TESTLIVE_RES,
    AT_4G_STARTUP_READBAUD,
    AT_4G_STARTUP_WAITFOR_READBAUD_RES,
    AT_4G_STARTUP_SETBAUD,
    AT_4G_STARTUP_WAITFOR_SETBAUD_RES,
    AT_4G_STARTUP_DIABLE_ECHO,
    AT_4G_STARTUP_WAITFOR_DIABLE_ECHO_RES,
    AT_4G_STARTUP_ENABLE_CMEE_ERR,
    AT_4G_STARTUP_WAITFOR_ENABLE_CMEE_ERR,
    AT_4G_STARTUP_QUERY_FUN,
    AT_4G_STARTUP_WAITFOR_QUERY_FUN_RES,
    AT_4G_STARTUP_SET_FUN,
    AT_4G_STARTUP_WAITFOR_SET_FUN,
    AT_4G_STARTUP_QUERY_COPS,
    AT_4G_STARTUP_WAITFOR_QUERY_COPS_RES,
    AT_4G_STARTUP_CONFIG_NETSCAN_MODE,
    AT_4G_STARTUP_WAITFOR_CONFIG_NETSCAN_MODE_RES,
    AT_4G_STARTIP_ENABLE_UPDATA_TIMEZONE,
    AT_4G_STARTIP_WAITFOR_ENABLE_UPDATA_TIMEZONE_RES,
    AT_4G_STARTUP_CONFIG_URC,
    AT_4G_STARTUP_WAITFOR_CONFIG_URC_RES,	
    AT_4G_STARTUP_URC_OTHER_OFF,
    AT_4G_STARTUP_URC_OTHER_OFF_RES,
    AT_4G_STARTUP_URC_RING,
    AT_4G_STARTUP_URC_RING_RES,
    AT_4G_STARTUP_URC_SMSINCOMING,
    AT_4G_STARTUP_URC_SMSINCOMING_RES,
    AT_4G_STARTUP_SEQ_FINISH,
    AT_4G_STARTUP_SEQ_STOP,
}AT_4G_STARTUP_STATE;

void at_4g_startup_init(void);

void at_4g_dostartup(void);

void at_4g_dostop_startup(void);

uint8 at_4g_get_start_state(void);

void at_4g_periodic(void);

#endif /* TBOX_4G_AT_STARTUP_H */
