#ifndef TBOX_4G_INFO_H
#define TBOX_4G_INFO_H

typedef enum
{
    INFO_4G_IDLE = 0,
    INFO_4G_DOQUERY,
    INFO_4G_TESTALIVE,
    INFO_4G_TESTALIVE_RES,
    INFO_4G_QUERY_SIM_INITSTATE,
    INFO_4G_WAITFOR_QUERY_SIM_INITSTATE_RES,
    INFO_4G_QUERY_IMEI,
    INFO_4G_WAITFOR_QUERY_IMEI_RES,
    INFO_4G_QUERY_IMSI,
    INFO_4G_WAITFOR_QUERY_IMSI_RES,
    INFO_4G_QUERY_ICCID,
    INFO_4G_WAITFOR_QUERY_ICCID_RES,
    INFO_4G_QUERY_CENTERNUM,
    INFO_4G_WAITFOR_QUERY_CENTERNUM_RES,
    INFO_4G_SELECT_PB_MEM,
    INFO_4G_WAITFOR_SELECT_PB_MEM_RES,
    INFO_4G_QUERY_PHONENUM,
    INFO_4G_WAITFOR_QUERY_PHONENUM_RES,
    INFO_4G_QUERY_CELLID,
    INFO_4G_WAITFOR_QUERY_CELLID_RES,
    INFO_4G_SET_SMS_PDUMODE,
    INFO_4G_WAITFOR_SET_SMS_PDUMODE_RES,
    INFO_4G_GET_OPERATOR,
    INFO_4G_WAITFOR_OPERATOR_RES,
    INFO_4G_QUERY_SIGNALSTRENGTH,
    INFO_4G_WAITFOR_QUERY_SIGNALSTRENGTH_RES,
    INFO_4G_QUERY_CREG,
    INFO_4G_WAITFOR_QUERY_CREG_RES,
    INFO_4G_QUERY_CGREG,
    INFO_4G_WAITFOR_QUERY_CGREG_RES,
    INFO_4G_QUERY_CEREG,
    INFO_4G_WAITFOR_QUERY_CEREG_RES,
    INFO_4G_QUERY_TEMPERATURE,
    INFO_4G_WAITFOR_QUERY_TEMPERATURE_RES,
    INFO_4G_QUERY_MTID,
    INFO_4G_WAITFOR_QUERY_MTID_RES,
    INFO_4G_QUERY_TAID,
    INFO_4G_WAITFOR_QUERY_TAID_RES,
    INFO_4G_FINISH,
    INFO_4G_STOP
}INFO_4G_STATE;

void info_4g_init(void);

void info_4g_doquery(void);

void info_4g_stop_query(void);

void info_4g_periodic(void);

uint8 info_4g_get_state(void);

#endif /* TBOX_4G_INFO_H */
