#ifndef __FOTA_CONTENT_H__
#define __FOTA_CONTENT_H__

#include "fota_if.h"

#define FOTA_CONTEXT_NAME		("FOTA_COM_CONTEXT")

#define FOTA_URL_MAX_LEN 		(256)
#define FOTA_TIME_MAX_LEN 		(6)
#define FOTA_MAGIC_NO			(0xABBACCDD)

#define FOTA_CYCLE_INTV			(1*1000)
#define FOTA_WAIT_ERASE_INTV	(5*1000)/FOTA_CYCLE_INTV
#define FOTA_WAIT_DOWNL_INTV	(10*1000)/FOTA_CYCLE_INTV
#define FOTA_DOWNL_TIMEOUT		(180*1000)/FOTA_CYCLE_INTV
#define FOTA_DOWNL_FINISH		(5*1000)/FOTA_CYCLE_INTV
#define FOTA_UPGRADE_TIMEOUT	(480*1000)/FOTA_CYCLE_INTV
#define FOTA_RESET_DELAY		(5*1000)/FOTA_CYCLE_INTV
#define FOTA_RESULT_DELAY		(5*1000)/FOTA_CYCLE_INTV

typedef enum
{
	FOTA_COM_IDLE = 0x00,
	FOTA_COM_DOWNLOAD,
	FOTA_COM_DOWNLOADING,
	FOTA_COM_DOWNLOAD_FINISH,
	FOTA_COM_CHECKSUM,
	FOTA_COM_HANDLE_RESET,
	FOTA_COM_HANDLE_RESULT,
}FOTA_COM_STATE_E;

typedef struct
{
	UINT32 magic;
	UINT16 state;
	UINT32 crc;
	UINT32 timeout;	
	UINT32 tick;
	UINT32 file_size;
	UINT16 url_len;
	UINT8  url[FOTA_URL_MAX_LEN];
	FOTA_RESULT_INFO_T reslut;
}FOTA_CONTEXT_T;

#endif
